// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB2CZNKVdGVTEvKZQ6PH5MNvHumo4sKnE',
    appId: '1:733585807546:web:3491bd7c292b0698e44a83',
    messagingSenderId: '733585807546',
    projectId: 'chatapp-42b50',
    authDomain: 'chatapp-42b50.firebaseapp.com',
    storageBucket: 'chatapp-42b50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOLtG4cmcs6QlwMrPzQnQz5reDgPFnlTs',
    appId: '1:733585807546:android:f50a13e5e88ec7eae44a83',
    messagingSenderId: '733585807546',
    projectId: 'chatapp-42b50',
    storageBucket: 'chatapp-42b50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNopPkCeJ31pf2moWFTI8f5THLlXUszM',
    appId: '1:733585807546:ios:98883da57abcbf33e44a83',
    messagingSenderId: '733585807546',
    projectId: 'chatapp-42b50',
    storageBucket: 'chatapp-42b50.appspot.com',
    iosBundleId: 'com.example.chatMessangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdNopPkCeJ31pf2moWFTI8f5THLlXUszM',
    appId: '1:733585807546:ios:98883da57abcbf33e44a83',
    messagingSenderId: '733585807546',
    projectId: 'chatapp-42b50',
    storageBucket: 'chatapp-42b50.appspot.com',
    iosBundleId: 'com.example.chatMessangerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB2CZNKVdGVTEvKZQ6PH5MNvHumo4sKnE',
    appId: '1:733585807546:web:381d22e1c50f94d4e44a83',
    messagingSenderId: '733585807546',
    projectId: 'chatapp-42b50',
    authDomain: 'chatapp-42b50.firebaseapp.com',
    storageBucket: 'chatapp-42b50.appspot.com',
  );
}
